### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by wojiaosun** [roadhan/FSCW#3]
hello  when i run " python train.py --data crossdomain.yaml --epochs 300 --weights yolov5x.pt --cfg yolov5x_FCM.yaml"
i got an  error  :dataset not found
![image](https://github.com/roadhan/FSCW/assets/132368019/6ceb6ca6-95f8-48f8-aead-b04208acc8c4)
how can i change the local datasets urpc,hope tp receive your response.

**Comment by snow102** [comment]
hello，I was wondering if you processed your dataset（urpc) yourself? Thank you for your answer

**Comment by roadhan** [comment]
> hello，I was wondering if you processed your dataset（urpc) yourself? Thank you for your answer

Since different data set segmentations may cause certain deviations in results when there are few-shot. the experimental results in the paper are averaged by the results of multiple random segmentations of the data set. We do not provide a specific segmentation method for the data set, you can segment and experiment according to your own ideas.

**Comment by snow102** [comment]
> > hello，I was wondering if you processed your dataset（urpc) yourself? Thank you for your answer
> 
> Since different data set segmentations may cause certain deviations in results when there are few-shot. the experimental results in the paper are averaged by the results of multiple random segmentations of the data set. We do not provide a specific segmentation method for the data set, you can segment and experiment according to your own ideas.

Okay, got it, thank you very much for your answer
